[package]
name = "paranoia_agent"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evtx = "0.7.2"
serde = "1.0.137"
serde_json = "1.0.81"
xml-rs = "0.8.4"
